### ISSUE TITLE
"go" naming collision

### ISSUE THREAD

**Issue by bitbrain** [jverhoelen/golumbus#5]
I just found out that the `go` command is already used by the _Go_ programming language. https://golang.org

I hope this will become no problem. Golumbus and the respective `goto` scripts will stop working as soon a user has installed a `Go` compiler.

**Comment by jonas-pietzsch** [comment]
I collected some thoughts about that the last hours and planning to make this configurable by the user. Personally, I have no associations to the Go language so there are no conflicts for me (initially, this project evolved from personal needs). But as other developers might have needs for Go language, it should be configurable, so you could simply define the command for golumbus on your own.

**Comment by jonas-pietzsch** [comment]
As configuring this would be tricky, so that `go` becomes some configurable command, I decided to overload the index.js script (with is the main) to be also executed on `gol`.

So Go lang users can also use the alternative command `gol` :)
