### ISSUE TITLE
cd: The directory 'Description: ' does not exist

### ISSUE THREAD

**Issue by bitbrain** [jverhoelen/golumbus#6]
When using the `goto.fish` function the user is not prompted to enter any description, which is strange behavior. When typing the following: `goto add 'my-location'` nothing is shown in fish shell. When typing any letter and pressing enter afterwards, the following error message occurs:

```
cd: The directory 'Description: ' does not exist
```

When the `goto` command is only for navigation a custom error message could be enough to tell the user to register locations with the `go` command.

**Comment by jonas-pietzsch** [comment]
Yeah, goto should only be proxying the go 'location' command. For all other operations, go should and can be used directly.
It should be made clear in the documentation, you're right.

**Comment by bitbrain** [comment]
Intererestingly when typing `goto add 'location'` the following happens:
1. `add` and `'location'` are passed as arguments to the `go` command
2. Golumbus executes with the given arguments, which results in the output `Description:`
3. `Description:` is returned to the `cd` command which results in the error described above

I think it must be ensured that `goto` only accepts one argument.

**Comment by jonas-pietzsch** [comment]
Alright. It's a very stupid piece of code right now, of course. Only works for what it is intended for atm.

**Comment by jonas-pietzsch** [comment]
Stays like it is. I won't fiddle with handling different shell argument usage (like fish compared to bash) for that. I will mention it in the README file that the `goto` command only does the one thing and is not intended for more :)
